### ISSUE TITLE
I am not sure what system refers to in the diagnosis table? 

### ISSUE THREAD

**Issue by annamoore1978** [RudolfCardinal/ithrive_data_extractor#4]
It may be that its not data that is meant to be queried, but when I try to I am getting a repeated error when I try and select system from diagnosis

SELECT
system
FROM
diagnosis

Connection ready. Took 0.022 seconds.

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'system
FROM
diagnosis' at line 2. (Error #1064) 0.000 seconds. (Line 1).

Finished. Total time: 0.022 seconds.

**Comment by RudolfCardinal** [comment]
I was sure that the problem was going to be that ``system`` was a reserved word, so you would have to do ``SELECT `system` FROM diagnosis``, per https://dev.mysql.com/doc/refman/8.0/en/identifiers.html.

But it's not that, and your code works fine in MySQL 5:

    USE ithrive;  -- this is what the database is called on my computer
    SELECT system FROM diagnosis;

or perhaps slightly more helpfully, a DISTINCT version:

    USE ithrive;
    SELECT DISTINCT system FROM diagnosis;

It's also fine without the closing semicolon.

So: not sure, but it's a problem at your end :) If ``system`` has become a keyword in your version of MySQL, just use the backtick quoting as above.

The results of the DISTINCT query are:

    system
    NCDS
    ICD-10
    DSM-IV

which should answer the other part of your question. Or, more generally, you can look at the DDL (either from the database or the Python tool's option to generate the DDL), or you can get the column descriptions like this:

    SELECT table_name, column_name, is_nullable, column_type, column_comment
    FROM information_schema.columns
    WHERE table_schema = 'ithrive'  -- assuming this is what you've called the database
    ORDER BY table_name, ordinal_position;
